//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLayer.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserSystemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserSystemResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLayer.Application.Resources.UserSystemResource", typeof(UserSystemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        internal static string Common_Name_Empty {
            get {
                return ResourceManager.GetString("Common_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆名不存在 的本地化字符串。
        /// </summary>
        internal static string Login_NameNotFound {
            get {
                return ResourceManager.GetString("Login_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆密码错误 的本地化字符串。
        /// </summary>
        internal static string Login_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆Token不能为空 的本地化字符串。
        /// </summary>
        internal static string Login_TokenEmpty {
            get {
                return ResourceManager.GetString("Login_TokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单已存在 的本地化字符串。
        /// </summary>
        internal static string Menu_Exists {
            get {
                return ResourceManager.GetString("Menu_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单不存在 的本地化字符串。
        /// </summary>
        internal static string Menu_NotExists {
            get {
                return ResourceManager.GetString("Menu_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色已存在 的本地化字符串。
        /// </summary>
        internal static string Role_Exists {
            get {
                return ResourceManager.GetString("Role_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色不存在 的本地化字符串。
        /// </summary>
        internal static string Role_NotExists {
            get {
                return ResourceManager.GetString("Role_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色组已存在 的本地化字符串。
        /// </summary>
        internal static string RoleGroup_Exists {
            get {
                return ResourceManager.GetString("RoleGroup_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色组不存在 的本地化字符串。
        /// </summary>
        internal static string RoleGroup_NotExists {
            get {
                return ResourceManager.GetString("RoleGroup_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已存在 的本地化字符串。
        /// </summary>
        internal static string User_Exists {
            get {
                return ResourceManager.GetString("User_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string User_NotExists {
            get {
                return ResourceManager.GetString("User_NotExists", resourceCulture);
            }
        }
    }
}
